### ISSUE TITLE
Got routing error while accessing to an error page

### ISSUE THREAD

**Issue by CharlyPoppins** [webfactory/exceptions-bundle#30]
Hi,

got this error while accessing to an inexistant page :

```
[2015-08-19 12:45:21] app.ERROR: An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "toto_home" as such route does not exist.") in "SiteTotoBundle:Modules/materiaux:nav-main.html.twig" at line 18. [] []
```

in my routing.yml hte route exists

```
toto_home:
    pattern:  /
    defaults: { _controller: SiteTotoBundle:Default:Home}
```

Don't understand why I have this error...

**Comment by MalteWunsch** [comment]
Sounds like a routing problem to me. What is the output of `app/console router:debug toto_home` and `app/console router:match /`?

Maybe your SiteTotoBundle is not registered in the Appkernel or the routing.yml is not included?

**Comment by CharlyPoppins** [comment]
You're right, I'm using JMSI18nRoutingBundle too, maybe that cause problem with the routing

```
router:debug toto_home    
  [InvalidArgumentException]              
  The route "toto_home" does not exist.  
                                      
router:match /
Route "fr__RG__toto_home" matches

[router] Route "fr__RG__toto_home"
Name         fr__RG__toto_home
Path         /
Path Regex   #^/$#s
Host         ANY
Host Regex   
Scheme       ANY
Method       ANY
Class        Symfony\Component\Routing\Route
Defaults     _controller: SiteTotoBundle:Default:Home
             _locale: fr
Requirements NO CUSTOM
Options      compiler_class: Symfony\Component\Routing\RouteCompiler
```

**Comment by CharlyPoppins** [comment]
Anyway, in my layout {{ path('toto_home') }} works fine, then in error.html.twig it causes an error...
```
{% extends "SiteTotoBundle:Default:layout.html.twig" %}
{% use "WebfactoryExceptionsBundle:Exception:blocks.html.twig" %}
{% block mainContent %}
<div class="g_container">
	{{ block('webfactory_exceptions_standardExceptionPage') }}
</div>
{% endblock %}
```

**Comment by MalteWunsch** [comment]
I don't know the JMSI18nRoutingBundle, but it seems to me it replaces your routes with multiple routes with internationalized names and somehow the path function translates the old name to a proper new one.

The failing `{{ path('toto_home') }}` seems to be located in `SiteTotoBundle:Modules/materiaux:nav-main.html.twig:18` and I guess that's included via your `SiteTotoBundle:Default:layout.html.twig`, right? If the layout works with your regular pages and doesn't do so with the error pages, it might be due to different environments we set up in the Controllers. [In the TestController we set the debug flag to false](https://github.com/webfactory/exceptions-bundle/blob/master/Controller/TestController.php#L31). Might that result in a different configuration of the JMSI18nRoutingBundle and/or implementations of the path function, could you check that by debugging?
